# wellness_orchestrator.py
import os
import traceback
from langgraph.graph import StateGraph, START, END
from langchain_core.messages import SystemMessage, HumanMessage
import asyncio

# Import agent and state components
from agents import (
    SentimentAgent,
    SocialAgent,
    HealthAgent,
    AgentState,
    generate_final_prompt
)

# Import the main WellnessAgent and context objects for the final step
from welness_agent import UserContext, WellnessAgent, WELLNESS_SYSTEM_PROMPT

# ------------------------------------------------------------------
# 1. Initialize Agent Instances
# ------------------------------------------------------------------

sentiment_agent = SentimentAgent()
social_agent = SocialAgent()
health_agent = HealthAgent()


# ------------------------------------------------------------------
# 2. Define the Graph Structure
# ------------------------------------------------------------------

def build_graph():
    """Builds and compiles the LangGraph multi-agent orchestration."""
    builder = StateGraph(AgentState)

    # Add nodes
    builder.add_node("sentiment_analysis", sentiment_agent.__call__)
    builder.add_node("social_suggestion", social_agent.__call__)
    builder.add_node("health_analysis", health_agent.__call__)
    builder.add_node("final_context_generation", generate_final_prompt)

    # Define edges - parallel execution of all three agents
    builder.add_edge(START, "sentiment_analysis")
    builder.add_edge(START, "social_suggestion")
    builder.add_edge(START, "health_analysis")

    # All three agents must complete before final generation
    builder.add_edge("sentiment_analysis", "final_context_generation")
    builder.add_edge("social_suggestion", "final_context_generation")
    builder.add_edge("health_analysis", "final_context_generation")

    # Exit after final generation
    builder.add_edge("final_context_generation", END)

    print("✓ Compiling LangGraph orchestration...")
    app = builder.compile()

    return app


# ------------------------------------------------------------------
# 3. Compile the Graph
# ------------------------------------------------------------------

app = build_graph()


# ------------------------------------------------------------------
# 4. The Orchestrator Function
# ------------------------------------------------------------------

async def run_orchestration(user_context: UserContext, on_session_end=None):
    """
    Kicks off the multi-agent orchestration and subsequently starts the voice session.

    Args:
        user_context: User context information
        on_session_end: Optional async callback function(reason: str) called when voice session ends
    """

    # 1. Prepare initial state
    initial_state = AgentState(
        messages=[],
        user_name=user_context.name,
        initial_mood=user_context.mood or "neutral",
        initial_health_data={
            "steps_today": user_context.health.steps_today if user_context.health else 0,
            "sleep_hours_last_night": user_context.health.sleep_hours_last_night if user_context.health else 0.0,
        },
        mood_score=5,
        mood_analysis="",
        social_suggestion="",
        health_score=50,
        health_suggestion="",
        final_context_prompt="",
    )

    print(f"\n{'=' * 60}")
    print(f"🚀 Starting Wellness Agent Orchestration for {user_context.name}")
    print(f"{'=' * 60}\n")

    try:
        # Run the graph
        print("📊 Running parallel agent analysis...")
        final_state = await app.ainvoke(initial_state, config={"recursion_limit": 10})

        print("\n✓ LangGraph orchestration complete!")
        print(f"\n{'=' * 60}")
        print("📋 Agent Results Summary:")
        print(f"{'=' * 60}")
        print(f"Mood Score: {final_state.get('mood_score', 'N/A')}/10")
        print(f"Mood Analysis: {final_state.get('mood_analysis', 'N/A')[:80]}...")
        print(f"Health Score: {final_state.get('health_score', 'N/A')}/100")
        print(f"Health Suggestion: {final_state.get('health_suggestion', 'N/A')[:80]}...")
        print(f"Social Suggestion: {final_state.get('social_suggestion', 'N/A')[:80]}...")
        print(f"{'=' * 60}\n")

    except Exception as e:
        print(f"\n❌ ERROR: LangGraph orchestration failed: {e}")
        traceback.print_exc()
        return

    # 3. Extract the final prompt
    final_prompt = final_state.get('final_context_prompt')

    if not final_prompt:
        print("❌ ERROR: Final prompt was not generated by the orchestration.")
        return

    print("✓ Final context prompt generated successfully!\n")

    # 4. Start the voice session
    print(f"{'=' * 60}")
    print("🎙️  Starting Voice Session with Wellness Agent")
    print(f"{'=' * 60}\n")

    api_key = os.environ.get("GEMINI_API_KEY")
    if not api_key:
        print("❌ ERROR: GEMINI_API_KEY is not set. Cannot start voice session.")
        return

    # Create the initial history with system prompt and generated context
    full_initial_history = [
        SystemMessage(content=WELLNESS_SYSTEM_PROMPT),
        HumanMessage(content=final_prompt)
    ]

    # Instantiate and start the wellness agent
    wellness_agent = WellnessAgent(api_key=api_key)

    try:
        await wellness_agent.start_voice_session_with_context(
            user_context=user_context,
            initial_history=full_initial_history,
            on_session_end=on_session_end  # Pass the callback through
        )
    except Exception as e:
        print(f"\n❌ ERROR: Voice session failed: {e}")
        traceback.print_exc()
    finally:
        print(f"\n{'=' * 60}")
        print("👋 Session ended. Thank you!")
        print(f"{'=' * 60}\n")


# ------------------------------------------------------------------
# 5. Main function for standalone testing
# ------------------------------------------------------------------

# Alias for backward compatibility
async def run_orchestration_with_callback(user_context: UserContext, on_session_end=None):
    """Alias for run_orchestration with callback support."""
    await run_orchestration(user_context, on_session_end)


async def main():
    """For testing the orchestrator directly."""
    from welness_agent import HealthSnapshot

    # Test context
    ctx = UserContext(
        name="Sagar",
        mood="a bit low on energy",
        health=HealthSnapshot(
            steps_today=2000,
            sleep_hours_last_night=5.0,
        ),
        conversation_summary="They felt stressed about work and wanted to improve their sleep habits.",
        goals="sleep better and be more active",
    )

    await run_orchestration(ctx)


if __name__ == "__main__":
    import sys

    if sys.platform == 'win32':
        asyncio.set_event_loop_policy(asyncio.WindowsSelectorEventLoopPolicy())

    try:
        asyncio.run(main())
    except KeyboardInterrupt:
        print("\n\n👋 Stopped by user.")