# wellness_orchestrator_live.py
"""
Enhanced wellness orchestrator with live transcript processing.
Runs initial analysis, then coordinates live agents during conversation.
"""

import os
import traceback
from langgraph.graph import StateGraph, START, END
from langchain_core.messages import SystemMessage, HumanMessage
import asyncio

# Import agent and state components
from agents import (
    SentimentAgent,
    SocialAgent,
    HealthAgent,
    AgentState,
    generate_final_prompt
)

# Import the enhanced WellnessAgent
from welness_agent_live import UserContext, WellnessAgentLive, WELLNESS_SYSTEM_PROMPT

# Initialize agent instances
sentiment_agent = SentimentAgent()
social_agent = SocialAgent()
health_agent = HealthAgent()


def build_graph():
    """Builds and compiles the LangGraph multi-agent orchestration."""
    builder = StateGraph(AgentState)

    # Add nodes
    builder.add_node("sentiment_analysis", sentiment_agent.__call__)
    builder.add_node("social_suggestion", social_agent.__call__)
    builder.add_node("health_analysis", health_agent.__call__)
    builder.add_node("final_context_generation", generate_final_prompt)

    # Define edges - parallel execution
    builder.add_edge(START, "sentiment_analysis")
    builder.add_edge(START, "social_suggestion")
    builder.add_edge(START, "health_analysis")

    # All agents complete before final generation
    builder.add_edge("sentiment_analysis", "final_context_generation")
    builder.add_edge("social_suggestion", "final_context_generation")
    builder.add_edge("health_analysis", "final_context_generation")

    builder.add_edge("final_context_generation", END)

    print("✓ Compiling LangGraph orchestration...")
    app = builder.compile()

    return app


app = build_graph()


async def run_orchestration_with_live_agents(user_context: UserContext, on_session_end=None):
    """
    Runs the initial multi-agent orchestration, then starts a voice session
    with continuous live agent analysis and real-time suggestions.

    Args:
        user_context: User context information
        on_session_end: Optional async callback function(reason: str) called when voice session ends
    """

    # 1. Prepare initial state for upfront analysis
    initial_state = AgentState(
        messages=[],
        user_name=user_context.name,
        initial_mood=user_context.mood or "neutral",
        initial_health_data={
            "steps_today": user_context.health.steps_today if user_context.health else 0,
            "sleep_hours_last_night": user_context.health.sleep_hours_last_night if user_context.health else 0.0,
        },
        mood_score=5,
        mood_analysis="",
        social_suggestion="",
        health_score=50,
        health_suggestion="",
        final_context_prompt="",
    )

    print(f"\n{'=' * 60}")
    print(f"🚀 Starting Wellness Agent Orchestration (Live Mode) for {user_context.name}")
    print(f"{'=' * 60}\n")

    try:
        # 2. Run initial LangGraph analysis
        print("📊 Running initial parallel agent analysis...")
        final_state = await app.ainvoke(initial_state, config={"recursion_limit": 10})

        print("\n✓ Initial LangGraph orchestration complete!")
        print(f"\n{'=' * 60}")
        print("📋 Initial Agent Results Summary:")
        print(f"{'=' * 60}")
        print(f"Mood Score: {final_state.get('mood_score', 'N/A')}/10")
        print(f"Mood Analysis: {final_state.get('mood_analysis', 'N/A')[:80]}...")
        print(f"Health Score: {final_state.get('health_score', 'N/A')}/100")
        print(f"Health Suggestion: {final_state.get('health_suggestion', 'N/A')[:80]}...")
        print(f"Social Suggestion: {final_state.get('social_suggestion', 'N/A')[:80]}...")
        print(f"{'=' * 60}\n")

    except Exception as e:
        print(f"\n❌ ERROR: Initial LangGraph orchestration failed: {e}")
        traceback.print_exc()
        return

    # 3. Extract the final prompt
    final_prompt = final_state.get('final_context_prompt')

    if not final_prompt:
        print("❌ ERROR: Final prompt was not generated by the orchestration.")
        return

    print("✓ Initial context prompt generated successfully!\n")

    # 4. Start the LIVE voice session with continuous agent monitoring
    print(f"{'=' * 60}")
    print("🎙️  Starting LIVE Voice Session with Real-Time Agent Analysis")
    print(f"{'=' * 60}\n")
    print("📡 Live agents will:")
    print("   • Monitor conversation transcripts in real-time")
    print("   • Analyze sentiment continuously")
    print("   • Provide dynamic social suggestions")
    print("   • Inject contextual insights every 45 seconds")
    print(f"{'=' * 60}\n")

    api_key = os.environ.get("GEMINI_API_KEY")
    if not api_key:
        print("❌ ERROR: GEMINI_API_KEY is not set. Cannot start voice session.")
        return

    # Create initial history with system prompt and generated context
    full_initial_history = [
        SystemMessage(content=WELLNESS_SYSTEM_PROMPT),
        HumanMessage(content=final_prompt)
    ]

    # Instantiate the LIVE wellness agent
    wellness_agent = WellnessAgentLive(api_key=api_key)

    try:
        await wellness_agent.start_voice_session_with_live_agents(
            user_context=user_context,
            initial_history=full_initial_history,
            on_session_end=on_session_end
        )
    except Exception as e:
        print(f"\n❌ ERROR: Voice session failed: {e}")
        traceback.print_exc()
    finally:
        print(f"\n{'=' * 60}")
        print("👋 Session ended. Thank you!")
        print(f"{'=' * 60}\n")


# Alias for backward compatibility
async def run_orchestration(user_context: UserContext, on_session_end=None):
    """Alias for the live orchestration function."""
    await run_orchestration_with_live_agents(user_context, on_session_end)


async def run_orchestration_with_callback(user_context: UserContext, on_session_end=None):
    """Alias for backward compatibility with callback support."""
    await run_orchestration_with_live_agents(user_context, on_session_end)


async def main():
    """For testing the orchestrator directly."""
    from welness_agent_live import HealthSnapshot

    # Test context
    ctx = UserContext(
        name="Sagar",
        mood="a bit low on energy",
        health=HealthSnapshot(
            steps_today=2000,
            sleep_hours_last_night=5.0,
        ),
        conversation_summary="They felt stressed about work and wanted to improve their sleep habits.",
        goals="sleep better and be more active",
    )

    await run_orchestration_with_live_agents(ctx)


if __name__ == "__main__":
    import sys

    if sys.platform == 'win32':
        asyncio.set_event_loop_policy(asyncio.WindowsSelectorEventLoopPolicy())

    try:
        asyncio.run(main())
    except KeyboardInterrupt:
        print("\n\n👋 Stopped by user.")